
const H=3600e3,D=24*H;
const GS={pending:['Pending approval','var(--cp-marigold)','var(--cp-on-marigold)','ph-hourglass-medium','Pending'],assigned:['Assigned','var(--cp-peacock)','#fff','ph-user-circle-check','Assigned'],progress:['In progress','var(--cp-pulse)','#fff','ph-hard-hat','In progress'],reopened:['Reopened','var(--cp-pulse-soft)','var(--cp-pulse-deep)','ph-arrow-counter-clockwise','Reopened'],fixed:['Fixed · confirming','var(--cp-leaf-soft)','var(--cp-ink)','ph-check','Fixed'],closed:['Closed','var(--cp-leaf)','#fff','ph-seal-check','Closed'],rejected:['Rejected','var(--cp-surface-2)','var(--cp-ink-3)','ph-x-circle','Rejected']};
const PINC={pending:'var(--cp-marigold)',assigned:'var(--cp-peacock)',progress:'var(--cp-pulse)',reopened:'var(--cp-pulse-deep)',fixed:'var(--cp-leaf)',closed:'var(--cp-leaf)',rejected:'var(--cp-ink-3)'};
const LIFE=[['Threshold','ph-users-three'],['Review','ph-scales'],['Assigned','ph-user-circle-check'],['Work','ph-hard-hat'],['Fixed','ph-check'],['Closed','ph-seal-check']];
const LI={pending:1,rejected:1,assigned:2,progress:3,reopened:3,fixed:4,closed:5};
const SEG=['var(--cp-marigold)','var(--cp-marigold)','var(--cp-peacock)','var(--cp-pulse)','var(--cp-leaf)','var(--cp-leaf)'];
const SEVL={critical:['Critical','var(--cp-pulse-soft)','var(--cp-pulse-deep)'],high:['High risk','var(--cp-pulse-soft)','var(--cp-pulse-deep)'],medium:['Medium','var(--cp-marigold-soft)','var(--cp-ink)'],low:['Low','var(--cp-surface-2)','var(--cp-ink-2)']};
const REASONS=[['Duplicate of an existing case','ph-copy'],['Outside our jurisdiction','ph-map-trifold'],['On private property','ph-house-line'],['Already resolved on inspection','ph-check-square'],['Not a civic issue','ph-prohibit'],['Evidence does not match site','ph-image-broken']];
const STF=[['all','All'],['pending','Pending approval'],['assigned','Assigned'],['progress','In progress'],['reopened','Reopened'],['overdue','Overdue'],['fixed','Fixed · confirming'],['closed','Closed'],['rejected','Rejected']];
const SORTS=[['score','Priority score'],['newest','Newest'],['sla','Target date'],['support','Most support']];
const DEPTS=[['Roads','Roads Team','ph-road-horizon'],['Water & Drainage','Water & Drainage Team','ph-drop'],['Sanitation','Sanitation Team','ph-trash'],['Streetlights','Streetlights Team','ph-lightbulb'],['Parks & Trees','Parks & Trees Team','ph-tree']];
const RAW2D={'Roads & Bridges':'Roads','Storm Water Drains':'Water & Drainage','Water & Sewerage':'Water & Drainage','Metrowater (CMWSSB)':'Water & Drainage','Solid Waste Mgmt':'Sanitation','Electrical':'Streetlights','Parks & Trees':'Parks & Trees'};
const DN=i=>RAW2D[i.dept]||i.dept;
const TM=i=>i.team||(DEPTS.find(d=>d[0]===DN(i))||[])[1]||'—';
const isoD=ts=>{const d=new Date(ts);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');};
const pd=v=>{const [y,m,d]=v.split('-').map(Number);return new Date(y,m-1,d).getTime();};
const ALLOW={pending:['assigned','rejected'],assigned:['progress'],progress:['fixed'],reopened:['fixed']};
const ACTL={'pending>assigned':'Drop to approve','pending>rejected':'Drop to reject','assigned>progress':'Drop to start work','progress>fixed':'Drop to mark fixed','reopened>fixed':'Drop to mark fixed'};
const BOARD=[['pending','Pending approval','Decide'],['assigned','Assigned','Start work'],['progress','In progress','Mark fixed'],['reopened','Reopened','Fix again'],['fixed','Fixed · confirming','Citizens confirm'],['closed','Closed','By citizens'],['rejected','Rejected','']];
const mulberry=a=>()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};
function genHist(){const rng=mulberry(20260927),out=[],now=Date.now(),by={};CP.get().issues.forEach(i=>{by[i.city]=by[i.city]||[];if(!by[i.city].includes(i.area))by[i.city].push(i.area);});
 const N={Chennai:620,Coimbatore:210,Madurai:190},RES={road:6,drain:4,garbage:1.5,light:2.5,water:3,tree:2,footpath:8},cats=Object.keys(CP.CATS),SL=[5,10,10,14];
 Object.keys(N).forEach(city=>{const ar=by[city]||[];if(!ar.length)return;for(let k=0;k<N[city];k++){const created=now-Math.pow(rng(),.85)*364*D-rng()*3*H;const mo=new Date(created).getMonth();let cat=cats[Math.floor(rng()*cats.length)];if(mo>=9&&mo<=11&&rng()<.4)cat=rng()<.6?'drain':'water';
  const area=ar[Math.min(ar.length-1,Math.floor(Math.pow(rng(),1.5)*ar.length))];const approved=rng()<.9;const dec=created+(3+rng()*44)*H;const due=dec+SL[Math.floor(rng()*4)]*D;let fixed=null,closed=null,reop=false;
  if(approved){let f=dec+RES[cat]*D*(.35+rng()*1.6)*(rng()<.1?2.6:1);if(rng()<.08){reop=true;f+=(2+rng()*5)*D;}if(f<now){fixed=f;if(f+1.5*D<now&&rng()<.93){closed=f+(.4+rng()*2.4)*D;if(closed>now)closed=null;}}}
  out.push({city,area,cat,dn:RAW2D[CP.CATS[cat].dept]||'Roads',created,dec,approved,fixed,closed,reop,due});}});return out;}
const fdate=ts=>new Date(ts).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'});
const T={en:{home:'Home',cases:'Cases',map:'Map',insights:'Insights',search:'Search',profile:'Profile',settings:'Settings'},ta:{home:'முகப்பு',cases:'வழக்குகள்',map:'வரைபடம்',insights:'பகுப்பாய்வு',search:'தேடல்',profile:'சுயவிவரம்',settings:'அமைப்புகள்'}};
const PKEY='koodal-gov-prefs',AKEY='koodal-gov-auth';
const DEF={notif:{threshold:true,sla:true,reopen:true,dispute:true,digest:false},ch:{push:true,email:true,sms:false},lang:'en',theme:'light',timeout:'30 min'};
const HN=[5,6,6,8,7,9,10,9,11,12,0,0],HC=[3,4,5,5,6,6,8,8,9,10,0,0];
const ME={name:'R. Ganesan',first:'Ganesan',ini:'RG',title:'Assistant Engineer',role:'Case Review Officer',dept:'Commissioner’s Grievance Cell',zone:'Zone 13 (Adyar) and adjoining southern wards',empId:'GCC-AE-10482',email:'r.ganesan@chennaicorporation.gov.in',phone:'+91 44 2561 9204',reports:'EE S. Meenakshi, Zone 13'};
const gs=i=>i.stage==='review'?'pending':i.stage==='rejected'?'rejected':i.stage==='closed'?'closed':i.stage==='resolved'?'fixed':(i.reopened?'reopened':i.stage==='progress'?'progress':'assigned');
const isCase=i=>!['reported','community'].includes(i.stage);
const overdue=i=>!!i.due&&i.due<Date.now()&&['verified','assigned','progress'].includes(i.stage);
const evTs=(i,re)=>{const e=i.events.filter(e=>re.test(e.title));return e.length?e[e.length-1].ts:null;};
const crossedAt=i=>evTs(i,/^Community verified/)||i.created;
const decTs=i=>evTs(i,/^(Verified by|Not accepted)/);
const fixTs=i=>evTs(i,/^Marked fixed/);
const ini=n=>n.replace(/^(JE|AE|EE)\s+/,'').split(' ').map(s=>s[0]).join('').slice(0,2);
const dur=ms=>{const h=ms/H;return h<48?Math.round(h)+'h':(h/24).toFixed(1).replace('.0','')+'d';};
const sdate=ts=>new Date(ts).toLocaleDateString('en-IN',{day:'numeric',month:'short'});
